-- supabase_schema.sql
-- Run this once in the Supabase SQL editor (Dashboard → SQL Editor → New query → paste → Run).

create table if not exists public.submissions (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  tasker_name   text,
  task_id       text not null,
  triage_note   text,
  skipped       boolean default false,
  skip_answers  jsonb default '{}'::jsonb,
  preseed_trace text,
  revised_trace text,
  preseed_plan  text,
  revised_plan  text,
  cameras       text[] default '{}',
  temporal      boolean default false,
  label_answers jsonb default '{}'::jsonb,
  section_results jsonb,
  revisions     jsonb,
  score         int,
  ai_analysis   jsonb,
  ai_verdict    text,
  major_flags   int default 0,
  minor_flags   int default 0
);

-- Helpful index for the reviewer dashboard
create index if not exists submissions_created_at_idx on public.submissions (created_at desc);
create index if not exists submissions_task_id_idx     on public.submissions (task_id);

-- Row Level Security: enabled, with NO public policies.
-- The app's API routes use the service_role key, which bypasses RLS, so the
-- table stays private (no anon access) while the server can still read/write.
alter table public.submissions enable row level security;

-- v3.4.0: open questions logged by the SOP assistant when it can't answer from the canonical doc
create table if not exists public.open_questions (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  question    text not null,
  asker_name  text,
  resolved    boolean not null default false
);
alter table public.open_questions enable row level security;

-- v3.5.0: per-issue feedback (Agree/Addressed/Disagree) for reviewer + future prompt tuning
create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  tasker_name text,
  task_id     text,
  code        text,          -- rubric code or 'grammar'/'sop'
  where_field text,          -- trace | plan
  severity    text,          -- major | minor | grammar | sop
  issue_fix   text,          -- the one-line fix that was shown
  issue_why   text,          -- the reasoning shown
  evidence    text,
  action      text,          -- 'addressed' | 'disagree'
  text_changed boolean,      -- did the revised text change vs when the issue was raised (for 'addressed')
  note        text           -- optional follow-up (e.g. confirmed-disagree after no-change prompt)
);
alter table public.feedback enable row level security;
